### ISSUE TITLE
h

### ISSUE THREAD

**Issue by woon-seng-hong-xinmin** [pendragons-code/School-stuffs#4]
does not include internal control

**Comment by woon-seng-hong-xinmin** [comment]
The depreciation file does not include what it mean it only includes what it isn't and why it is.

**Comment by woon-seng-hong-xinmin** [comment]
Sort the items in folders and make it neater

**Comment by woon-seng-hong-xinmin** [comment]
accrual basis spelt whether as weather. Also made some typos beow.

**Comment by woon-seng-hong-xinmin** [comment]
income and expenses, prepaid or received in advance

**Comment by woon-seng-hong-xinmin** [comment]
business types and their differences

**Comment by pendragons-code** [comment]
Resolved
